image: adnrv/opencv

# Script variables
variables:
    INPUT_DIR:  "input"
    OUTPUT_DIR: "output"

stages:
  - prepare
  - test
  - report

# Preparation stage
prepare:
  stage: prepare
  script:
    - make clean prepare
  artifacts:
    paths:
      - ${INPUT_DIR}/*
    
# Stage to test pipeline
test:
  stage: test
  script:
    - pip install -r requirements1.txt
    - pip install -r requirements2.txt
    - make run
  artifacts:
    paths:
      - ${OUTPUT_DIR}/klt/*
      - ${OUTPUT_DIR}/keypoints/*
      - ${OUTPUT_DIR}/sfm/hotel.ply
  dependencies:
    - prepare


# Stage to produce the report
report:
  image: adnrv/texlive:full
  stage: report
  script:
    - cd report
    - latexmk -pdf -pdflatex="pdflatex --shell-escape %O %S" report
    # move the file to the root folder
    - mv report.pdf ../
    - rm -f *.out *.aux *.alg *.acr *.dvi *.gls *.log *.bbl *.blg *.ntn *.not *.lof *.lot *.toc *.loa *.lsg *.nlo *.nls *.ilg *.ind *.ist *.glg *.glo *.xdy *.acn *.idx *.loq *~
  artifacts:
    paths:
      - report.pdf
